name: More Actions

on: [pull_request, push]

jobs:
  inspect_env_context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "GITHUB_BASE_REF '$GITHUB_BASE_REF'"
      - run: echo "GITHUB_HEAD_REF '$GITHUB_HEAD_REF'"
      - run: echo "GITHUB_REF '$GITHUB_REF'"
      - run: echo "GITHUB_SHA '$GITHUB_SHA'"
      # Does the following even exist?
      - run: echo "GITHUB_COMMIT_RANGE '$GITHUB_COMMIT_RANGE'"
      - name: Dump github context
        run: echo '${{ toJSON(github) }}'
      - run: exit 2